---

- hosts: localhost

  tasks:

    - name: Install dependencies (CentOS/RHEL)
      yum: name={{ item }} state=present
      with_items:
        - nfs-utils
        - xorg-x11-xauth
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Install dependencies (Ubuntu/Debian)
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - xrdp
        - mate-desktop
        - mate-session-manager
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Setup startwm.sh
      copy: src=startwm.sh dest=/etc/xrdp/startwm.sh owner=root group=root mode=644 backup=yes
      notify: restart xrdp

  handlers:
    - name: restart xrdp
      command: service xrdp restart
